package blog.robertotavares.cemversiculos.data.repository.categories

val afirmacoes_energia = listOf(
"Acordo todos os dias com uma vitalidade que transborda de dentro para fora.",
"Meu corpo é uma fonte inesgotável de energia quando o trato com cuidado e respeito.",
"Sinto uma força interior poderosa que me impulsiona em direção ao que desejo.",
"Cada célula do meu corpo vibra com saúde, disposição e vitalidade plena.",
"Minha energia se renova naturalmente quando me permito descansar com intenção.",
"Carrego comigo uma vitalidade contagiante que eleva os ambientes que habito.",
"Sou um canal de energia positiva que flui livremente através de mim.",
"Meu entusiasmo pelo que faço é o combustível que me mantém em movimento constante.",
"Tenho disposição abundante para enfrentar os desafios do dia com leveza e vigor.",
"Minha energia vital se expande quando vivo alinhado com meu propósito mais profundo.",
"Cuido do meu corpo com consciência, alimentando a energia que preciso para viver plenamente.",
"Sinto-me revigorado após o descanso, pronto para dar o melhor de mim a cada novo dia.",
"Minha mente e meu corpo trabalham em harmonia, gerando um estado de vitalidade constante.",
"Tenho energia mais que suficiente para realizar tudo que é verdadeiramente importante para mim.",
"Cada respiração profunda que faço renova minha disposição e clareza mental.",
"Sou naturalmente atraído por hábitos que amplificam minha vitalidade e bem-estar.",
"Minha energia não depende das circunstâncias externas — ela nasce de dentro.",
"Sinto um fogo interno que me anima mesmo nos dias em que o cansaço tenta me vencer.",
"Meu corpo responde com vigor quando o movimento, a nutrição e o sono se alinham.",
"Carrego uma presença energética que inspira e motiva as pessoas ao meu redor.",
"Sou capaz de recuperar minha energia rapidamente após períodos de esforço intenso.",
"Minha vitalidade é uma expressão direta do amor e cuidado que invisto em mim mesmo.",
"Tenho a sabedoria de gerir minha energia com inteligência, gastando-a no que realmente vale.",
"Sinto meu corpo forte, minha mente ativa e meu espírito em plena efervescência.",
"Cada manhã é uma recarga completa que me prepara para viver com intensidade.",
"Minha energia flui com equilíbrio entre ação e descanso, entre esforço e recuperação.",
"Sou grato pela vitalidade que meu corpo expressa quando o trato com amor.",
"Tenho energia criativa em abundância para transformar ideias em realidade concreta.",
"Meu entusiasmo é genuíno e se renova toda vez que me conecto com meu propósito.",
"Sinto-me vivo, presente e vibrante em cada momento que escolho estar plenamente aqui.",
"Minha disposição mental é tão poderosa quanto minha energia física.",
"Carrego leveza no corpo e clareza na mente, o que multiplica minha capacidade de agir.",
"Sou capaz de sustentar altos níveis de energia ao longo do dia com hábitos conscientes.",
"Minha alimentação nutre cada célula do meu corpo, gerando vitalidade de dentro para fora.",
"Tenho a energia necessária para perseguir meus sonhos sem abrir mão do meu equilíbrio.",
"Sinto meu corpo se fortalecer progressivamente a cada escolha saudável que faço.",
"Minha energia emocional é estável, o que me permite agir com clareza mesmo sob pressão.",
"Cada movimento que faço — físico, mental ou espiritual — é carregado de intenção e força.",
"Sou uma pessoa vibrante que irradia saúde, alegria e disposição genuína.",
"Tenho reservas profundas de energia que se revelam nos momentos em que mais preciso.",
"Minha vitalidade cresce quando sirvo, quando crio e quando me conecto com o que amo.",
"Sinto meu coração forte e meu corpo disposto para enfrentar qualquer jornada que me espera.",
"Minha energia se eleva naturalmente quando me cerco de pessoas e ambientes positivos.",
"Tenho o poder de transformar cansaço em renovação através do descanso intencional.",
"Sou capaz de iniciar cada tarefa com disposição total, independentemente do horário.",
"Minha energia espiritual sustenta minha energia física nos momentos de maior exigência.",
"Cada noite de sono reparador é um investimento direto na minha vitalidade do dia seguinte.",
"Tenho uma relação consciente com minha energia — sei quando avançar e quando recuar.",
"Sinto uma corrente de entusiasmo circulando em mim quando penso nas possibilidades da minha vida.",
"Meu corpo é resiliente, adaptável e capaz de se regenerar com velocidade surpreendente.",
"Sou apaixonado pelo que faço e essa paixão é uma fonte inesgotável de energia.",
"Tenho clareza sobre o que drena minha energia e me afasto disso com consciência e firmeza.",
"Minha disposição não é resultado do acaso — é fruto de escolhas diárias e intencionais.",
"Sinto minha energia se expandir quando agio com autenticidade e alinhamento com meus valores.",
"Cada desafio superado deposita mais força e vitalidade no meu reservatório interno.",
"Minha energia é renovável porque cultivo práticas que a restauram com consistência.",
"Tenho um corpo que responde com entusiasmo quando o convido para o movimento e a ação.",
"Sinto uma leveza crescente no corpo e na mente conforme libero o que não me serve mais.",
"Minha vitalidade é um reflexo direto do propósito que carrego em cada passo que dou.",
"Sou capaz de manter alta performance sem sacrificar meu bem-estar e equilíbrio interior.",
"Cada copo d'água, cada refeição nutritiva, é um ato de amor que amplia minha energia.",
"Minha força não é apenas muscular — ela é mental, emocional e espiritual em igual medida.",
"Tenho energia mais do que suficiente para ser presente para as pessoas que amo.",
"Sinto meu corpo revigorado e minha mente afiada quando respeito meus ritmos naturais.",
"Minha energia criativa flui livremente quando estou descansado, alimentado e em paz.",
"Sou uma pessoa de ação — e essa ação nasce de uma energia interior profunda e estável.",
"Tenho a sabedoria de proteger minha energia como o recurso mais precioso que possuo.",
"Sinto uma vitalidade expansiva que me permite viver cada dia com presença e intensidade.",
"Meu corpo sabe se recuperar e eu confio nessa inteligência orgânica que me habita.",
"Cada prática que incorporo na minha rotina amplifica minha disposição de forma cumulativa.",
"Sou naturalmente energético quando estou alinhado com quem verdadeiramente sou.",
"Tenho o entusiasmo de quem sabe que cada dia é uma oportunidade irrepetível.",
"Minha energia se multiplica quando colaboro, quando crio e quando contribuo com algo maior.",
"Sinto meu sistema nervoso calmo e meu corpo cheio de uma energia limpa e sustentável.",
"Cada vez que escolho me mover em vez de me paralisar, minha vitalidade se fortalece.",
"Minha disposição é contagiante e transforma positivamente os ambientes que frequento.",
"Tenho uma fonte interior de motivação que não se esgota porque está ligada ao meu propósito.",
"Sinto energia fluindo por cada parte do meu ser quando vivo com autenticidade e intenção.",
"Meu corpo é forte, minha mente é clara e meu espírito está em plena harmonia.",
"Cada manhã que acordo é uma prova de que tenho energia e propósito para mais um dia.",
"Sou capaz de transformar esforço em resultado porque minha energia está bem direcionada.",
"Tenho a vitalidade de quem cuida de si mesmo com amor e a determinação de quem sabe o que quer.",
"Minha energia não se dispersa em preocupações — ela se concentra em possibilidades.",
"Sinto meu corpo como um aliado poderoso que trabalha a meu favor a cada momento.",
"Cada escolha saudável que faço é um depósito direto no meu banco de energia vital.",
"Sou capaz de sustentar minha vitalidade ao longo de semanas e meses com consistência.",
"Minha energia interior é silenciosa, profunda e muito mais poderosa do que aparenta.",
"Tenho disposição para começar, persistência para continuar e força para concluir.",
"Sinto meu entusiasmo crescer naturalmente quando me aproximo do que tem sentido real para mim.",
"Minha vitalidade é uma expressão da minha saúde integral — corpo, mente e espírito alinhados.",
"Sou cheio de uma energia que serve, que cria, que transforma e que inspira.",
"Cada dia bem vivido recarrega minha alma e prepara meu corpo para o que vier a seguir.",
"Tenho energia abundante para viver plenamente, amar profundamente e contribuir genuinamente.",
"Minha força vital é real, crescente e está disponível para mim sempre que preciso dela.",
)