package blog.robertotavares.cemversiculos.data.repository.categories

val afirmacoes_paz = listOf(
    "Carrego dentro de mim um silêncio profundo que nenhuma circunstância externa consegue romper.",
    "Minha paz interior é um alicerce sólido que sustenta cada decisão que tomo.",
    "Escolho responder à vida com serenidade, mesmo quando ela me apresenta turbulências.",
    "Há um centro calmo dentro de mim que permanece estável independentemente do caos ao redor.",
    "Solto o que não posso controlar e encontro paz profunda nesse gesto de entrega.",
    "Minha mente descansa com facilidade quando confio que tudo está se desenrolando como deve.",
    "Vivo em harmonia comigo mesmo, com os outros e com o fluxo natural da vida.",
    "A serenidade que habita meu coração é mais forte do que qualquer ansiedade que tenta me visitar.",
    "Escolho a paz não como fuga, mas como uma postura ativa e consciente diante da vida.",
    "Meu sistema nervoso relaxa naturalmente quando me lembro de que estou seguro agora.",
    "Encontro tranquilidade no momento presente, que é o único lugar onde a vida realmente acontece.",
    "Libero o passado com gratidão e o futuro com confiança, vivendo em paz no agora.",
    "Minha paz não depende de aprovação, de perfeição ou de circunstâncias favoráveis.",
    "Sou capaz de encontrar quietude mesmo em meio ao movimento acelerado do dia a dia.",
    "Cada respiração profunda me ancora no presente e dissolve qualquer tensão acumulada.",
    "Tenho a sabedoria de escolher batalhas que merecem minha energia e soltar o resto.",
    "Meu coração está em paz com as escolhas que fiz e confiante nas que ainda farei.",
    "Vivo com uma leveza crescente conforme aprendo a soltar o que não me pertence.",
    "A paz que encontro em mim mesmo se irradia para as relações e ambientes ao meu redor.",
    "Sou capaz de permanecer centrado mesmo quando as pessoas e situações ao meu redor oscilam.",
    "Minha mente não precisa resolver tudo agora — confio que as respostas chegam no momento certo.",
    "Escolho pensar pensamentos que me aproximam da paz em vez de me afundar na preocupação.",
    "Há uma vastidão tranquila dentro de mim que é maior do que qualquer problema que enfrento.",
    "Sou em paz com quem sou, com onde estou e com tudo que ainda estou me tornando.",
    "Minha serenidade é genuína — ela não é supressão de emoções, mas sim equilíbrio verdadeiro.",
    "Confio no processo da vida e essa confiança me liberta de uma ansiedade desnecessária.",
    "Encontro paz no simples, no ordinário, nos pequenos momentos que compõem minha vida.",
    "Meu descanso é profundo porque minha consciência está em paz com o que vivo.",
    "Libero a necessidade de controlar tudo e descubro que a vida flui melhor assim.",
    "Sou capaz de atravessar conflitos sem perder minha paz interior como ponto de referência.",
    "A calma que cultivo internamente me permite tomar decisões mais sábias e mais claras.",
    "Minha paz é um presente que ofereço ao mundo simplesmente sendo quem sou.",
    "Tenho a capacidade de me reconectar com minha serenidade em qualquer momento do dia.",
    "Escolho soltar ressentimentos porque a paz que ganho vale infinitamente mais do que qualquer razão.",
    "Minha mente tranquila é o ambiente ideal para que criatividade e sabedoria floresçam.",
    "Sou em paz com meu passado — ele me moldou sem me aprisionar.",
    "Encontro harmonia interior quando alinho minhas ações com meus valores mais profundos.",
    "A paz que sinto não é ausência de desafios — é a presença de uma confiança inabalável.",
    "Meu coração perdoa com facilidade porque sei que a paz é sempre a melhor escolha.",
    "Sou capaz de sentar com o silêncio e encontrar nele conforto em vez de desconforto.",
    "Libero a urgência artificial e me permito viver no ritmo que é naturalmente meu.",
    "Minha serenidade se aprofunda a cada prática de presença e atenção plena.",
    "Tenho paz com as minhas imperfeições porque sei que elas fazem parte da beleza de ser humano.",
    "Cada momento de quietude que cultivo é um investimento na minha saúde integral.",
    "Sou capaz de ouvir minha voz interior com clareza quando minha mente está em paz.",
    "Minha tranquilidade interior não é fragilidade — é uma força que poucos desenvolvem.",
    "Escolho não alimentar conflitos internos que apenas consomem minha energia vital.",
    "Encontro paz profunda na aceitação do que é, sem deixar de trabalhar pelo que pode ser.",
    "Meu espírito está em harmonia com a vida, e essa harmonia me sustenta em todos os momentos.",
    "Sou capaz de me desapegar de resultados e encontrar paz genuína no processo.",
    "A serenidade que carrego comigo transforma os ambientes que habito de forma silenciosa.",
    "Minha mente descansa no presente porque é aqui que a paz verdadeiramente mora.",
    "Tenho a coragem de buscar paz mesmo quando o mundo ao redor celebra a agitação.",
    "Sou em paz com o ritmo único da minha jornada, sem pressa e sem comparações.",
    "Cada gesto de perdão que ofereço a mim mesmo aprofunda minha paz interior.",
    "Minha serenidade cresce na mesma proporção em que solto o que não posso mudar.",
    "Encontro equilíbrio entre agir com determinação e confiar com tranquilidade.",
    "Sou capaz de receber notícias difíceis sem perder meu centro de calma e equanimidade.",
    "Minha paz interior é uma conquista diária que renovo com cada escolha consciente.",
    "Tenho a sabedoria de reconhecer que a maioria das preocupações não merece minha paz.",
    "Sou em harmonia com o tempo — nem preso no passado nem ansioso pelo futuro.",
    "Cada prática de silêncio e meditação aprofunda o oceano de paz que habita em mim.",
    "Minha tranquilidade não é indiferença — é uma presença amorosa e consciente diante da vida.",
    "Sou capaz de discordar sem perder a paz, de lutar sem perder a serenidade.",
    "Encontro paz genuína quando paro de lutar contra o que é e começo a trabalhar com o que há.",
    "Meu coração está livre de mágoas antigas porque escolhi a paz como meu estado natural.",
    "Tenho a habilidade de transformar ansiedade em curiosidade e tensão em presença.",
    "Sou em paz com a incerteza porque confio que sou capaz de lidar com o que vier.",
    "Minha serenidade é tão profunda que até as tempestades passam sem me destruir.",
    "Cada limite saudável que estabeleço é um ato direto de preservação da minha paz interior.",
    "Sou capaz de me desconectar do ruído externo e mergulhar na quietude que me restaura.",
    "Minha paz se fortalece cada vez que escolho responder em vez de reagir impulsivamente.",
    "Tenho dentro de mim um reservatório de calma ao qual posso acessar em qualquer momento.",
    "Sou em paz com o mistério da vida — nem tudo precisa de explicação para ser aceito.",
    "Encontro harmonia quando sirvo, quando amo e quando vivo com genuína autenticidade.",
    "Minha tranquilidade interior é independente das opiniões, dos julgamentos e das expectativas alheias.",
    "Sou capaz de atravessar períodos de grande mudança sem perder meu senso de estabilidade.",
    "Cada vez que escolho a paz em vez da reatividade, me torno mais inteiro e mais livre.",
    "Minha mente em paz é o solo fértil onde as melhores ideias e decisões nascem.",
    "Tenho a graciosidade de aceitar o que não posso mudar e a coragem de transformar o que posso.",
    "Sou em paz com as pessoas que me decepcionaram — liberei o peso e guardei o aprendizado.",
    "Encontro serenidade profunda na natureza, no silêncio e nos momentos de pura contemplação.",
    "Minha paz interior é um farol que orienta meus passos mesmo quando a visibilidade é baixa.",
    "Sou capaz de viver com simplicidade e encontrar nela uma riqueza que o excesso nunca oferece.",
    "Minha serenidade não é conquistada — ela é revelada quando solto tudo que a encobria.",
    "Tenho paz com o tempo que as coisas levam, sabendo que o amadurecimento tem seu próprio ritmo.",
    "Sou em paz com minha humanidade — com meus limites, minhas contradições e meu crescimento.",
    "Cada noite que adormeço em paz é uma renovação completa para o dia que está por vir.",
    "Minha tranquilidade é real, profunda e disponível para mim a qualquer instante que eu a invocar.",
    "Tenho a paz de quem sabe que está no caminho certo, mesmo quando ele ainda não está completo.",
    "Sou um ponto de quietude no mundo — e essa quietude tem um impacto que vai além do que vejo.",
    "Minha paz não é um destino que ainda vou alcançar — ela é uma escolha que faço agora.",
    "Encontro harmonia em cada aspecto da minha vida quando vivo alinhado com minha essência.",
    "Sou capaz de existir em paz com o presente, esperançoso com o futuro e reconciliado com o passado.",
    "A paz que habita em mim é inabalável, crescente e genuinamente minha.",
)